### ISSUE TITLE
regex syntax problem in isc-bind-9.10.2pl3 on openbsd

### ISSUE THREAD

**Issue by sasskinn12** [tommyblue/Bind-Log-Analyzer#4]
First, great project!
I have couple issues exporting my log to database using Bind-Log-Analyzer. I am not goot in ruby so is it possible to fix regex for bind 9.10 ? my output line looks like this:

25-Nov-2015 10:29:53.073 client 192.168.16.7#60458 (host.example.com): query: host.example.com IN A + (192.168.16.1)

I compared it to yours output , seems i have an extra (host.example.com) in my query :(

Tnx

**Comment by tommyblue** [comment]
hi @sasskinn12 could you please provide a log file with more examples so I can use that file to test this improvement

**Comment by sasskinn12** [comment]
Sure here is log, btw in my named.conf logging configured this way:
```
logging {
        channel querylog{
                file "named-query.log" ;
                print-time yes;
                print-severity no;
                print-category no;
        };
                category queries { querylog;};
};
```
[named-query.txt](https://github.com/tommyblue/Bind-Log-Analyzer/files/43710/named-query.txt)

**Comment by renardarg** [comment]
hi, nice project but can not make it work, on debian jessie  Bind 9.9.5, got the same log syntax : 
client 192.168.30.11#25760 (mtalk.google.com): query: mtalk.google.com IN A + (192.168.30.250)

named.conf is : 
logging{
    channel "querylog" {
            file "/var/log/bind/query.log";
               print-time yes;
               print-severity no;
               print-category no;
    };
    category queries { querylog; };
};

when  i try #bind_log_analyzer -f /var/log/bind/query.log -v 3 i get 
E, [2015-12-04T10:26:37.835938 #28077] ERROR -- : Can't parse the line: "client 192.168.30.11#55165 (mtalk.google.com): query: mtalk.google.com IN A + (192.168.30.250)
"
(mtalk.google.com) seems to be to much in log 

thanks

**Comment by sasskinn12** [comment]
Jep, seems like you have same issue as me, because of bind version i am afraid..

**Comment by joecoolio** [comment]
I have the same problem as sasskinn12 above.  The () before "query:" is breaking the regexp.

This doesn't work
28-Jan-2016 17:53:16.468 client 127.0.0.1#53468** (ppa.launchpad.net)**: query: ppa.launchpad.net IN A + (127.0.0.1)

This works:
28-Jan-2016 17:53:16.468 client 127.0.0.1#53468: query: ppa.launchpad.net IN A + (127.0.0.1)

More non-working examples:

28-Jan-2016 17:53:16.468 client 127.0.0.1#33410 (security.ubuntu.com): query: security.ubuntu.com IN A + (127.0.0.1)
28-Jan-2016 17:53:16.496 client 127.0.0.1#49195 (security.ubuntu.com): query: security.ubuntu.com IN AAAA + (127.0.0.1)
28-Jan-2016 17:53:16.915 client 127.0.0.1#49729 (ppa.launchpad.net): query: ppa.launchpad.net IN AAAA + (127.0.0.1)
28-Jan-2016 17:53:27.629 client 127.0.0.1#55875 (news.sunnyusenet.com): query: news.sunnyusenet.com IN A + (127.0.0.1)
28-Jan-2016 17:53:27.740 client 127.0.0.1#45888 (news.sunnyusenet.com): query: news.sunnyusenet.com IN AAAA + (127.0.0.1)
28-Jan-2016 17:53:42.740 client 127.0.0.1#48593 (us.archive.ubuntu.com): query: us.archive.ubuntu.com IN A + (127.0.0.1)
28-Jan-2016 17:53:42.764 client 127.0.0.1#46900 (us.archive.ubuntu.com): query: us.archive.ubuntu.com IN AAAA + (127.0.0.1)
28-Jan-2016 17:53:42.790 client 127.0.0.1#56689 (security.ubuntu.com): query: security.ubuntu.com IN A + (127.0.0.1)
28-Jan-2016 17:53:42.814 client 127.0.0.1#41217 (security.ubuntu.com): query: security.ubuntu.com IN AAAA + (127.0.0.1)

**Comment by tommyblue** [comment]
Fixed in version 0.2.4. Now supports both new and old log versions

**Comment by dmfrey** [comment]
I just set this up. I seem to be getting this similar others on raspbian jessie

    E, [2016-03-05T19:37:56.176186 #3650] ERROR -- : Can't parse the line: "03-Mar-2016 21:36:47.901 client 192.168.100.105#39709 (cm.g.doubleclick.net): query: cm.g.doubleclick.net IN A + (192.168.100.2)

Version: 1:9.9.5.dfsg-9+deb8u5
Architecture: armhf

**Comment by sasskinn12** [comment]
You need to pull lastest rev. of bindanalyzer :)

**Comment by tommyblue** [comment]
This is strange, I just added you log to the tests and it's passing:
https://github.com/tommyblue/Bind-Log-Analyzer/commit/19007e28920b78649ef9a9baa2fc6038ed3fda11#diff-ca55bccb7ffb2f60d0ef467ea7f60b33R68

I just pushed the new 0.2.4 version to rubygems.org, try updating the gem

**Comment by tommyblue** [comment]
Ok, my fault. The rubygems version wasn't the one with the fixed parser. Just update the gem and it should work.
sorry :sob:

**Comment by dmfrey** [comment]
I just updated as well and now it seems to be parsing. Still some failures
in there, but it looks like it is moving along.  Do I need to add those
other logging configurations, besides the line in the doc just to print the
time?

**Comment by tommyblue** [comment]
mmm, sorry? I'm getting the last part..

**Comment by dmfrey** [comment]
do i need to add these to my logging config?

    print-severity no;
    print-category no;

the readme only states:

    print-time yes;

**Comment by tommyblue** [comment]
I'd say no (or at least for the first version it wasn't needed), but I'm not using any bind server at the moment so trying by yourself and see what happens (or asking @sasskinn12) could be the only solution
